[theme]
base = "dark"
primaryColor = "#06b6d4"
backgroundColor = "#0b0f19"
secondaryBackgroundColor = "#111827"
textColor = "#f3f4f6"
font = "sans serif"

[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 1000

[browser]
gatherUsageStats = false
